---
mariadb__delegate_to: example_db # Must specify the host name for docker (because docker doesn't have ssh service)
mariadb__users:
  - name: '{{ application_database_user }}'
    database: '{{ application_database_name }}'
    host: "{{ hostvars['example_web']['ansible_default_ipv4']['address'] }}"
