gwecweb:
  container_name: gwecweb
  restart: always
  image: beatada/ansible:trusty
  ports:
    - "80:80"
  command: tail -f /dev/null

gwecdb:
  container_name: gwecdb
  restart: always
  image: beatada/ansible:trusty
  expose:
    - "3306"
  command: tail -f /dev/null
