# For development purpose
# - Persistant data storage
# - Mount project directory as v
gwecweb:
  container_name: gwecweb
  restart: always
  image: beatada/ansible:trusty
  ports:
    - "80:80"
  volumes:
    - ./web:/srv/www/sites/shop # Mount project directory to the web folder, the path to document root is '/srv/www/shop/public', see `inventory/group_vars/web_servers.yml`
  command: tail -f /dev/null

gwecdata:
  container_name: gwecdata
  image: tianon/true
  volumes:
    - /var/lib/mysql

gwecdb:
  container_name: gwecdb
  restart: always
  image: beatada/ansible:trusty
  expose:
    - "3306"
  volumes_from:
    - gwecdata
  command: tail -f /dev/null
